sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk
      - docker-ce

services: docker

install: chef exec bundle

# Ensure we make ChefDK's Ruby the default
before_script:
  - eval "$(chef shell-init bash)"
  - docker --version

script:
  - chef exec berks
  - chef exec rspec
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify
