name "dokku"
maintainer "Nick Charlton"
maintainer_email "nick@nickcharlton.net"
license "mit"
description "Manages a dokku install."
long_description "Manages a dokku install and provides LWRPs for managing apps."
version "2.1.0"

depends "apt", "~> 7.1.0"
depends "docker", "~> 4.6.5"
depends "packagecloud", "~> 1.0.0"
depends "openssl", "~> 8.5.5"

recipe "default", "Triggers install cookbooks and provides the LWRP."
recipe "install", "Installs and configures dokku dependencies"
recipe "plugins", "Installs and configures plugins"
recipe "ssh_keys", "Installs and configures ssh_keys"
recipe "certificates", "Configures certificates for dokku apps"
